# Site settings
title: Andrew Koszela - A blog about Andrew
email: AndrewKoszela@gmail.com
description: A blog about my favorite person Andrew.
url: "http://andrewkoszela@gmail.com" # the base hostname & protocol for your site
baseurl: '/andrewsite'
twitter_username: AndrewKoszela

# Build settings
markdown: kramdown
permalink: /:title
